version: '3.8'

services:
  app:
    build:
      context: ../../
      dockerfile: docker/laravel/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - keycloak-network

networks:
  keycloak-network:
    driver: bridge